- include: check_vars.yml
  tags:
    - haproxy
    - check

- include: haproxy.yml
  tags:
    - haproxy

- include: letsencrypt.yml
  when: haproxy_letsencrypt_manage
  tags:
    - haproxy
    - letsencrypt

